### ISSUE TITLE
Is it possible to create training model larger than 128x128?

### ISSUE THREAD

**Issue by room3dev** [shaoanlu/faceswap-GAN#60]
There is the limitation for doing this?

**Comment by shaoanlu** [comment]
We can make the model generate larger images with little modification on the scripts. But the bottleneck is training data: we have to prepare high quality training data that has at least same resolution with desired output resolution. Also, the training time will be much longer (O(n^2)?) with increasing input/output resolution, and I simply don't have enough resource to do any experiment on such configuration.

**Comment by room3dev** [comment]
I want to give a try for only a few swap images (not hundred video frames) to test If it works 
so I think training time is not a problem here, please tell me how I do this.

**Comment by shaoanlu** [comment]
Models can not generate high resolution images without training it. It not transferable between different output size.

**Comment by room3dev** [comment]
Yes, I know that can not be reused for different size model.
but is it okay If I edit code like this? It just work or I need to do anything else?
```
# 3. Config 
IMAGE_SHAPE = (**256, 256**, 3) 
....
# 4. Define model section
def Discriminator(nc_in, input_size=**256**): 
.... 
def Encoder(nc_in=3, input_size=**256**):
....

```

**Comment by room3dev** [comment]
OK, I will try.
Thanks!

**Comment by oatssss** [comment]
Did you get this to work? I changed those values for `IMAGE_SHAPE`, `Discriminator`, and `Encoder` in [`FaceSwap_GAN_v2_sz128_train.ipynb`](https://github.com/shaoanlu/faceswap-GAN/blob/master/FaceSwap_GAN_v2_sz128_train.ipynb) but am now getting an error about dimensions mismatching:

```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 128 and 256 for 'mul_1' (op: 'Mul') with input shapes: [?,128,128,1], [?,256,256,3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\machine-learning\faceswap-GAN\FaceSwap_GAN_v2_sz256_train_new.py", line 166, in <module>
    distorted_A, fake_A, fake_sz64_A, mask_A, path_A, path_mask_A, path_abgr_A, path_bgr_A = cycle_variables(netGA)
  File "D:\machine-learning\faceswap-GAN\FaceSwap_GAN_v2_sz256_train_new.py", line 158, in cycle_variables
    masked_fake_output = alpha * rgb + (1-alpha) * distorted_input
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 907, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1131, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "C:\Python36\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 3100, in _mul
    "Mul", x=x, y=y, name=name)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3208, in _create_op_helper
    set_shapes_for_outputs(op)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "C:\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 128 and 256 for 'mul_1' (op: 'Mul') with input shapes: [?,128,128,1], [?,256,256,3].
```
